In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [14]:
from pandas import Series, DataFrame
dataset1={'age','bp','al','su','bgr','bu','sc','sod','pot','hrmo','pcv','wc','rc'}
dataset2={
    'rbc':['abnormal','normal'],
    'pc':['abnormal','normal'],
    'pcc':['notpresent','present'],
    'ba':['notpresent','present'],
    'htn':['no','yes'],
    'dm':['no','yes'],
    'cad':['no','yes'],
    'appet':['poor','yes'],
    'pe':['poor','yes'],
    'ane':['no','yes']
}
df1=pd.DataFrame(dataset2)
dummies1=pd.get_dummies(df1,prefix=['rbc','pc','pcc','ba','htn','dm','cad','appet','pe','ane'])
dataset3={'sg':['a','b','c','d']}
df2=pd.DataFrame(dataset3)
dummies2=pd.get_dummies(df2,prefix=['sg'])
print(dummies1)
print(dummies2)

   rbc_abnormal  rbc_normal  pc_abnormal  pc_normal  pcc_notpresent  \
0          True       False         True      False            True
1         False        True        False       True           False

   pcc_present  ba_notpresent  ba_present  htn_no  htn_yes  dm_no  dm_yes  \
0        False           True       False    True    False   True   False
1         True          False        True   False     True  False    True

   cad_no  cad_yes  appet_poor  appet_yes  pe_poor  pe_yes  ane_no  ane_yes
0    True    False        True      False     True   False    True    False
1   False     True       False       True    False    True   False     True
    sg_a   sg_b   sg_c   sg_d
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True

In [18]:
df=pd.concat([dataset1,dummies1.reset_index(drop=True),dummies2.reset_index(drop=True)],axis='columns',ignore_index=True)
print(df)

TypeError: cannot concatenate object of type '<class 'set'>'; only Series and DataFrame objs are valid

In [16]:
dataset['index']
indep=dataset[["age","bp","sg","al","su","rbc","pc","pcc","ba","bgr","bu","sc","sod","pot","hrmo","pcv","wc","rc","htn","dm","cad","appet","pe","ane"]]
dep=dataset["classification"]

KeyError: 'index'

In [ ]:
indep.shape
dep

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)